<a href="https://colab.research.google.com/github/ayshaasif/MachineLearning/blob/main/00_Introduction_to_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



```
#Introduction to TensorFlow
```



In [1]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#checking the dimensions
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([10, 4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  4], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
#create a matrix
matrix = tf.constant([[3.,5.],
                      [4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 5.],
       [4., 5.]], dtype=float32)>

In [7]:
matrix.ndim

2

In [8]:
tensor = tf.constant([
    [[1,2,3],[2.,8,7]],
    [[34,65,7],[7,8,5]],
     [[1,2,3],[2.,8,7]],
    [[34,65,7],[7,8,5]]
                      
                      ])
tensor

<tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[ 1.,  2.,  3.],
        [ 2.,  8.,  7.]],

       [[34., 65.,  7.],
        [ 7.,  8.,  5.]],

       [[ 1.,  2.,  3.],
        [ 2.,  8.,  7.]],

       [[34., 65.,  7.],
        [ 7.,  8.,  5.]]], dtype=float32)>

In [9]:
tensor.ndim

3

**Creating Tensor with tf.Variable**

In [10]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [11]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [12]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Creating random tensor

In [13]:
#creating random tensorswith tensorFlow

In [15]:
random_1 = tf.random.Generator.from_seed(7)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_3 = tf.random.Generator.from_seed(3)
random_1,random_2, random_3

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tensorflow.python.ops.stateful_random_ops.Generator at 0x7f5d4fc37e50>)

Shuffle the order of elements in the tensor

In [16]:
not_shuffled = tf.constant([[10,7],[8,9],[9,0]])


## Neural Network with Tensorflow

Regression Problem